# Generated by Django 3.1.4 on 2023-07-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ('-created_at',)},
        ),
    ]
